name: Get Citation Data

on: 
  schedule:
    - cron:  '0 8 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        cd ./google_scholar_crawler
        pip install -r requirements.txt
    - name: Run citation crawler
      run: |
        cd ./google_scholar_crawler
        python main.py
      env: 
        GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
    - name: Commit and push results
      run: |
        git config --local user.name "${GITHUB_ACTOR}"
        git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add google_scholar_crawler/results/*.json
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Updated Citation Data [skip ci]"
          git push
        fi